# Generated by Django 4.1.7 on 2023-04-13 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_itementrega'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itementrega',
            name='produto',
        ),
        migrations.RemoveField(
            model_name='itementrega',
            name='quantidade',
        ),
        migrations.AddField(
            model_name='entrega',
            name='quantidade',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itementrega',
            name='tipo_volume_extra',
            field=models.CharField(choices=[('bebidas', 'Bebidas'), ('frios_congelados', 'Frios/Congelados'), ('vassouras_rodo', 'Vassouras/Rodo'), ('outros', 'Outros')], default=None, max_length=16),
            preserve_default=False,
        ),
    ]
