# Generated by Django 4.1.7 on 2023-04-13 14:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_itementrega_produto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrega',
            name='data_compra',
            field=models.DateField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entrega',
            name='hora_entrega',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entrega',
            name='nome_do_embalador',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entrega',
            name='numero_nfce',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
